//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AzurLane.Extractor.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Cli {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Cli() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AzurLane.Extractor.Localization.Cli", typeof(Cli).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executable adb path to pull files in android devices.
        /// </summary>
        public static string Adb {
            get {
                return ResourceManager.GetString("Adb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If an apk file is provided, we will extract AssetBundles from it also..
        /// </summary>
        public static string Apk {
            get {
                return ResourceManager.GetString("Apk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;AssetBundles path in android device.\nUsually it looks like \&quot;/storage/emulated/0/Android/data/com.bilibili.azurlane/files/AssetBundles\&quot;.
        /// </summary>
        public static string AssetsPathInDevice {
            get {
                return ResourceManager.GetString("AssetsPathInDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset folders&apos; names to extract.\n Default is [painting, paintingface].
        /// </summary>
        public static string AssetTypes {
            get {
                return ResourceManager.GetString("AssetTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 从Asset Studio导出的资源中提取出完整图片.
        /// </summary>
        public static string ExtractOptions {
            get {
                return ResourceManager.GetString("ExtractOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ip address for connecting an android device..
        /// </summary>
        public static string Ip {
            get {
                return ResourceManager.GetString("Ip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local unzipped assets for merging..
        /// </summary>
        public static string LocalAssetsPath {
            get {
                return ResourceManager.GetString("LocalAssetsPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 合并安卓设备、本地和Apk文件里的资源.
        /// </summary>
        public static string MergeOptions {
            get {
                return ResourceManager.GetString("MergeOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory for output files..
        /// </summary>
        public static string Output {
            get {
                return ResourceManager.GetString("Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port for connecting an android device.
        /// </summary>
        public static string Port {
            get {
                return ResourceManager.GetString("Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Texture and mesh directory..
        /// </summary>
        public static string TexAndMeshPath {
            get {
                return ResourceManager.GetString("TexAndMeshPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug info. TBD.
        /// </summary>
        public static string Verbose {
            get {
                return ResourceManager.GetString("Verbose", resourceCulture);
            }
        }
    }
}
